### ISSUE TITLE
Build fails with npm

### ISSUE THREAD

**Issue by denisshepelin** [tj/node-discount#3]
When installing 
npm install markdown
configure finished successfully
but then got errorrs

Waf: Entering directory `/home/denis/.nvm/v0.1.103/lib/node/.npm/markdown/0.1.2/package/build'
[1/2] cxx: src/markdown.cc -> build/default/src/markdown_1.o
[2/2] cxx_link: build/default/src/markdown_1.o -> build/default/markdown.node
/usr/bin/ld: /usr/local/lib/libmarkdown.a(mkdio.o): relocation R_X86_64_32 against 
`fgetc' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libmarkdown.a: could not read symbols: Bad value
collect2: ld returned 1 exit status

**Comment by tj** [comment]
do you have discount installed? `brew install discount`

**Comment by denisshepelin** [comment]
Yes. but I'am not using  brew
I'am on linux. I've just made 
./configure make 
sudo make install
source was latest from git

**Comment by tj** [comment]
ah gotcha, k i did the same thing and get can reproduce the error, not sure what the problem is ATM but I will try and look into it soon

**Comment by denisshepelin** [comment]
I hope u can fix this. Good luck!

**Comment by dpritchett** [comment]
I just got this working on Ubuntu 10.04.  I had to download and install Discount manually:

```
git clone git://github.com/Orc/discount.git
cd discount
./configure
make && make install
npm install markdown
```

Done.

**Comment by codedmart** [comment]
dpritchett - I installed discount just like that but I am still getting the same error as posted above. Are you on 64bit Ubuntu. I am not sure why I am getting this error.

**Comment by peterhost** [comment]
Debian Lenny 64bits
For info, same issue with debian Lenny. Either from the prepackaged discount & libmarkdown-dev from repository http://debian.zecrazytux.net/, or after installing discount from source. 
I need to look into it further

__

EDIT : ok, so problem is (on 64bit debian/ubuntu) that library `libmarkdown.a` is not by default compiled  with PIC (Position-Independent Code) option on these systems.

quick and dirty fix

Patch "`Makefile.in`" in your "discount" build tree, with this diff :

> 1c1
> 
> < CC=@CC@ -I. -L. -fPIC
> 
> ---
> 
> > CC=@CC@ -I. -L.

Far from perfect as all is then compiled with -fPIC, but worked for me

**Comment by RubenVerborgh** [comment]
The above doesn't work for me on Ubuntu 11.04 (64bit). I get:

```
[2/2] cxx_link: build/default/src/markdown_1.o -> build/default/markdown.node
/usr/bin/ld: /usr/local/lib/libmarkdown.a(tags.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libmarkdown.a: could not read symbols: Bad value
collect2: ld returned 1 exit status
Waf: Leaving directory `/tmp/node-discount/build'
Build failed:  -> task failed (err #1): 
    {task: cxx_link markdown_1.o -> markdown.node}
```

I compiled with `-fPIC`. Any thoughts?

**Comment by RubenVerborgh** [comment]
After some fiddling, it does. Never mind!

**Comment by imstand** [comment]
working after brew install discount
